package com.dasbikash.news_server_data_coordinator_rest_jersey.repositories

import com.dasbikash.news_server_data_coordinator_rest_jersey.model.database.ArticleDeleteRequest
import org.springframework.data.jpa.repository.JpaRepository

interface ArticleDeleteRequestRepository : JpaRepository<ArticleDeleteRequest, Int>